[theme]
base            = "dark"
primaryColor    = "#6366f1"
backgroundColor = "#04080f"
secondaryBackgroundColor = "#0a1020"
textColor       = "#f0f6ff"
font            = "sans serif"

[server]
headless      = true
port          = 8501
enableCORS    = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
serverAddress    = "localhost"

[runner]
fastReruns = true

[client]
showErrorDetails = true
toolbarMode      = "minimal"
