# utils/email_sender.py
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
import os


# CONFIGURE YOUR EMAIL HERE
SENDER_EMAIL = "your_hospital_email@gmail.com"
SENDER_PASSWORD = "your_app_password"     # Use Gmail App Password
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587


def send_report_email(to_email, patient_name, patient_id, pdf_path):
    """
    Send a patient's PDF report to doctor or patient email.
    
    Setup: In Gmail → Account → Security → App Passwords → Create one
    Paste that 16-char password as SENDER_PASSWORD above.
    """
    try:
        msg = MIMEMultipart()
        msg["From"] = SENDER_EMAIL
        msg["To"] = to_email
        msg["Subject"] = f"Onco AI Report — Patient {patient_id} ({patient_name})"

        body = f"""
Dear Doctor / Patient,

Please find attached the AI-generated breast cancer diagnosis report for:

    Patient Name: {patient_name}
    Patient ID: {patient_id}

This report was generated by the Onco AI Breast Cancer Detection System.

IMPORTANT DISCLAIMER:
This report is for clinical decision support only. 
All findings must be reviewed and confirmed by a qualified medical professional.

---
Onco AI System — AI Powered Medical Diagnosis Platform
        """

        msg.attach(MIMEText(body, "plain"))

        # Attach PDF
        with open(pdf_path, "rb") as f:
            part = MIMEBase("application", "octet-stream")
            part.set_payload(f.read())
            encoders.encode_base64(part)
            part.add_header(
                "Content-Disposition",
                f"attachment; filename=report_{patient_id}.pdf"
            )
            msg.attach(part)

        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.starttls()
        server.login(SENDER_EMAIL, SENDER_PASSWORD)
        server.send_message(msg)
        server.quit()

        return True, "Email sent successfully!"

    except Exception as e:
        return False, f"Email failed: {str(e)}"


def send_alert_email(to_email, patient_name, patient_id, diagnosis_result, confidence):
    """
    Send an urgent alert for Malignant detection.
    """
    if diagnosis_result != "Malignant":
        return False, "Alert only for Malignant cases"

    try:
        msg = MIMEMultipart()
        msg["From"] = SENDER_EMAIL
        msg["To"] = to_email
        msg["Subject"] = f"🚨 URGENT — Malignant Detection: Patient {patient_id}"

        body = f"""
⚠️ URGENT CLINICAL ALERT

The Onco AI System has detected a MALIGNANT finding for:

    Patient Name: {patient_name}
    Patient ID: {patient_id}
    AI Result: MALIGNANT
    Confidence: {confidence:.2f}%
    Time: Auto-detected

IMMEDIATE ACTION REQUIRED:
Please schedule an oncologist consultation for this patient.

This is an automated alert from the Onco AI Breast Cancer Detection System.
All findings require professional medical verification.
        """

        msg.attach(MIMEText(body, "plain"))
        server = smtplib.SMTP(SMTP_SERVER, SMTP_PORT)
        server.starttls()
        server.login(SENDER_EMAIL, SENDER_PASSWORD)
        server.send_message(msg)
        server.quit()

        return True, "Alert email sent!"

    except Exception as e:
        return False, f"Alert failed: {str(e)}"