# pages/27_Send_Email.py
import streamlit as st
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from auth.guard import check_login
from database.database import connect, log_audit
from utils.sidebar import render_sidebar
from utils.language import get_text
import os

check_login()
lang = render_sidebar()

st.markdown("""
<style>
.email-card {
    background: linear-gradient(145deg, #0f172a, #1e293b);
    border: 1px solid rgba(99,102,241,0.25);
    border-radius: 16px; padding: 28px; margin-bottom: 16px;
}
.stApp { background: #060b18; }
section[data-testid="stSidebar"] { background: #0a0f1e !important; }
</style>
""", unsafe_allow_html=True)

st.title("📧 Send Email — Reports & Alerts")
st.write("Send diagnosis reports and urgent alerts to doctors and patients via email.")

# ── Gmail Setup Instructions ──────────────────────────────────────────────────
with st.expander("⚙️ Gmail Setup (First Time Only — Read This)"):
    st.markdown("""
    **Steps to enable Gmail sending:**

    1. Go to [myaccount.google.com](https://myaccount.google.com)
    2. Click **Security** → **2-Step Verification** → Enable it
    3. Go back to Security → search **App Passwords**
    4. Select App: **Mail** → Select Device: **Windows Computer**
    5. Click **Generate** → Copy the 16-character password
    6. Paste that password below as **Gmail App Password**

    ✅ This is safe — your main Gmail password stays secret.
    """)

# ── Email credentials input ───────────────────────────────────────────────────
st.subheader("📬 Email Configuration")
col1, col2 = st.columns(2)
with col1:
    sender_email = st.text_input("Your Gmail Address", placeholder="yourhospital@gmail.com")
with col2:
    sender_pass  = st.text_input("Gmail App Password (16 chars)", type="password",
                                 placeholder="xxxx xxxx xxxx xxxx")

st.markdown("---")
tab1, tab2, tab3 = st.tabs(["📄 Send Report Email", "🚨 Send Malignant Alert", "📢 Bulk Announcement"])

# ── TAB 1: Send Report ────────────────────────────────────────────────────────
with tab1:
    st.subheader("Send Patient Report to Doctor / Patient")

    col1, col2 = st.columns(2)
    with col1:
        report_pid   = st.text_input("Patient ID", key="rpt_pid")
        to_email_rpt = st.text_input("Send to Email", placeholder="doctor@hospital.com", key="rpt_email")
    with col2:
        patient_name_rpt = st.text_input("Patient Name", key="rpt_name")
        subject_rpt = st.text_input("Email Subject",
            value="Onco AI — Breast Cancer Diagnosis Report", key="rpt_subj")

    body_rpt = st.text_area("Email Body", value=f"""Dear Doctor,

Please find attached the AI-generated breast cancer diagnosis report.

Patient ID   : {report_pid if report_pid else '[Patient ID]'}
Patient Name : {patient_name_rpt if patient_name_rpt else '[Patient Name]'}

This report was generated by the Onco AI Breast Cancer Detection System.

IMPORTANT: This is an AI-assisted report for clinical decision support only.
All findings must be reviewed and confirmed by a qualified medical professional.

---
Onco AI System — CMR University
AI Powered Medical Diagnosis Platform
    """, height=200, key="rpt_body")

    pdf_upload = st.file_uploader("Attach PDF Report (optional)", type=["pdf"], key="rpt_pdf")

    if st.button("📤 Send Report Email", type="primary", key="send_rpt"):
        if not sender_email or not sender_pass:
            st.error("Please enter your Gmail and App Password above.")
        elif not to_email_rpt:
            st.error("Please enter recipient email.")
        else:
            try:
                msg = MIMEMultipart()
                msg["From"]    = sender_email
                msg["To"]      = to_email_rpt
                msg["Subject"] = subject_rpt
                msg.attach(MIMEText(body_rpt, "plain"))

                if pdf_upload:
                    part = MIMEBase("application", "octet-stream")
                    part.set_payload(pdf_upload.read())
                    encoders.encode_base64(part)
                    part.add_header("Content-Disposition",
                                    f"attachment; filename=report_{report_pid}.pdf")
                    msg.attach(part)

                server = smtplib.SMTP("smtp.gmail.com", 587)
                server.starttls()
                server.login(sender_email, sender_pass)
                server.send_message(msg)
                server.quit()

                log_audit("EMAIL_REPORT", sender_email,
                          f"Report sent to {to_email_rpt} for patient {report_pid}")
                st.success(f"✅ Report email sent successfully to **{to_email_rpt}**!")
                st.balloons()
            except smtplib.SMTPAuthenticationError:
                st.error("❌ Gmail authentication failed. Check your App Password (not your normal Gmail password).")
            except Exception as e:
                st.error(f"❌ Email failed: {str(e)}")

# ── TAB 2: Malignant Alert ────────────────────────────────────────────────────
with tab2:
    st.subheader("🚨 Send Urgent Alert for Malignant Detection")
    st.warning("Use this to immediately notify doctor when AI detects MALIGNANT result.")

    col1, col2 = st.columns(2)
    with col1:
        alert_pid    = st.text_input("Patient ID",   key="alert_pid")
        alert_name   = st.text_input("Patient Name", key="alert_name")
        alert_conf   = st.number_input("AI Confidence (%)", min_value=0.0, max_value=100.0,
                                       value=86.12, key="alert_conf")
    with col2:
        alert_email  = st.text_input("Doctor Email", placeholder="doctor@hospital.com", key="alert_email")
        alert_doctor = st.text_input("Doctor Name",  key="alert_doc")
        alert_date   = st.text_input("Detection Time", key="alert_date")

    if st.button("🚨 Send URGENT Alert", type="primary", key="send_alert"):
        if not sender_email or not sender_pass:
            st.error("Please enter your Gmail and App Password above.")
        elif not alert_email:
            st.error("Please enter doctor's email.")
        else:
            try:
                msg = MIMEMultipart()
                msg["From"]    = sender_email
                msg["To"]      = alert_email
                msg["Subject"] = f"🚨 URGENT — Malignant Detection: Patient {alert_pid}"

                body = f"""
⚠️ URGENT CLINICAL ALERT — ONCO AI SYSTEM

The AI has detected a MALIGNANT finding requiring immediate attention.

━━━━━━━━━━━━━━━━━━━━━━━━━━
Patient ID   : {alert_pid}
Patient Name : {alert_name}
AI Result    : MALIGNANT
Confidence   : {alert_conf:.2f}%
Detected at  : {alert_date}
━━━━━━━━━━━━━━━━━━━━━━━━━━

IMMEDIATE ACTION REQUIRED:
Please schedule an oncologist consultation for this patient within 24 hours.

This is an automated alert from the Onco AI Breast Cancer Detection System.
All findings require professional medical verification.

---
Onco AI System — CMR University
AI Powered Medical Diagnosis Platform
                """
                msg.attach(MIMEText(body, "plain"))

                server = smtplib.SMTP("smtp.gmail.com", 587)
                server.starttls()
                server.login(sender_email, sender_pass)
                server.send_message(msg)
                server.quit()

                log_audit("EMAIL_ALERT", sender_email,
                          f"MALIGNANT alert sent to {alert_email} for patient {alert_pid}")
                st.error(f"🚨 URGENT ALERT sent to **{alert_email}** — Dr. {alert_doctor}")
                st.balloons()
            except smtplib.SMTPAuthenticationError:
                st.error("❌ Gmail authentication failed. Check your App Password.")
            except Exception as e:
                st.error(f"❌ Alert failed: {str(e)}")

# ── TAB 3: Bulk Announcement ──────────────────────────────────────────────────
with tab3:
    st.subheader("📢 Send Announcement to All Staff")
    st.info("Send a notice to multiple doctors/staff at once.")

    recipients = st.text_area(
        "Recipient Emails (one per line)",
        placeholder="doctor1@hospital.com\ndoctor2@hospital.com\nnurse@hospital.com",
        height=120
    )
    bulk_subject = st.text_input("Subject", value="Onco AI System — Important Announcement")
    bulk_body    = st.text_area("Message", height=200,
        value="""Dear Medical Staff,

This is an announcement from the Onco AI Breast Cancer Detection System.

[Your message here]

---
Onco AI System — CMR University
AI Powered Medical Diagnosis Platform""")

    if st.button("📢 Send to All", type="primary", key="send_bulk"):
        if not sender_email or not sender_pass:
            st.error("Please enter your Gmail and App Password above.")
        elif not recipients.strip():
            st.error("Please enter at least one recipient email.")
        else:
            emails = [e.strip() for e in recipients.strip().split("\n") if e.strip()]
            success, failed = [], []
            for email in emails:
                try:
                    msg = MIMEMultipart()
                    msg["From"]    = sender_email
                    msg["To"]      = email
                    msg["Subject"] = bulk_subject
                    msg.attach(MIMEText(bulk_body, "plain"))

                    server = smtplib.SMTP("smtp.gmail.com", 587)
                    server.starttls()
                    server.login(sender_email, sender_pass)
                    server.send_message(msg)
                    server.quit()
                    success.append(email)
                except Exception as e:
                    failed.append(f"{email} ({str(e)})")

            log_audit("EMAIL_BULK", sender_email, f"Bulk sent to {len(success)} recipients")

            if success:
                st.success(f"✅ Sent to {len(success)} recipients: {', '.join(success)}")
            if failed:
                st.error(f"❌ Failed for: {', '.join(failed)}")

# ── Email Log ─────────────────────────────────────────────────────────────────
st.markdown("---")
st.subheader("📋 Email Audit Log")
import pandas as pd
conn = connect()
try:
    df_log = pd.read_sql_query(
        "SELECT action, user, details, created FROM audit_log WHERE action LIKE 'EMAIL%' ORDER BY created DESC LIMIT 20",
        conn
    )
    if not df_log.empty:
        st.dataframe(df_log, use_container_width=True)
    else:
        st.info("No emails sent yet.")
except:
    st.info("No email log found.")
conn.close()
